# Generated by Django 2.2.19 on 2022-09-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220929_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
